### ISSUE TITLE
Integration into quickfix list?

### ISSUE THREAD

**Issue by liamtimms** [Canop/nvim-bacon#1]
I notice that `BaconList` seems to open its own UI with its own color scheme on my system, which is somewhat jarring. It might be nicer to integrate `BaconList` into the concept of a Quick Fix List which is already part of vim/neovim and is the usual place for compiler errors as I understand it.

**Comment by Canop** [comment]
@liamtimms You're probably much more experienced than me regarding this. I'd welcome your help there, be it with technical references, a PR, a fork, or a completely new project, as you feel better.

What matters most for me is the ability to keep the same interaction with bacon and the shortcuts to see all items and choose one or to go to the next one.

**Comment by Canop** [comment]
@liamtimms Can we close this issue now that @ConnorWay32 did the quicklist integration ?
