### ISSUE TITLE
 both race conditions 

### ISSUE THREAD

**Issue by davehorner** [Canop/nvim-bacon#20]
> You may notice it loads the list (:BaconLoad) then saves the current document (:w), to prevent both **race conditions and having a bunch of unsaved buffers.**
 
 It's not clear to the reader what race conditions or unsaved buffers we're avoiding.  Why can't we leave unsaved buffers laying around?

**Comment by davehorner** [comment]
I guess that makes sense, you can't point into a modified file.  the race condition could still use a little expansion. #9 has been around for a while; no race condition with that solution?

**Comment by Canop** [comment]
This comment just to say that your comments aren't unnoticed, I'm just lacking time at the moment but I'll come back to this.

**Comment by davehorner** [comment]
No problem at all; appreciate all your effort and have a great week!  I was reading it wrong too as both race conditions...it was "both race conditions and unsaved buffers"; its early.  it's not an issue.
